apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flash-sale-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flash-sale-app # 對應到您的 Deployment 名稱
  minReplicas: 1         # 平常最少維持 1 個
  maxReplicas: 10        # 流量大時最多開到 10 個
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # 當 CPU 超過 50% 就擴容